# Generated by Django 2.2 on 2022-08-23 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm_base', '0002_farm_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farm',
            old_name='owner',
            new_name='owner_id',
        ),
    ]
